# Generated by Django 5.2.8 on 2025-11-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartitionedEnrollment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'adbms_demo_partitionedenrollment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NonPartitionedEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        # Create partitioned table with partitions
        migrations.RunSQL(
            sql="""
                CREATE TABLE adbms_demo_partitionedenrollment (
                    id SERIAL,
                    student_name VARCHAR(100) NOT NULL,
                    course_code VARCHAR(20) NOT NULL,
                    semester VARCHAR(20) NOT NULL,
                    grade VARCHAR(2)
                ) PARTITION BY LIST (semester);
                
                -- Create partitions for different semesters
                CREATE TABLE adbms_demo_partitionedenrollment_fall2024 
                    PARTITION OF adbms_demo_partitionedenrollment 
                    FOR VALUES IN ('Fall 2024');
                    
                CREATE TABLE adbms_demo_partitionedenrollment_spring2025 
                    PARTITION OF adbms_demo_partitionedenrollment 
                    FOR VALUES IN ('Spring 2025');
                    
                CREATE TABLE adbms_demo_partitionedenrollment_fall2025 
                    PARTITION OF adbms_demo_partitionedenrollment 
                    FOR VALUES IN ('Fall 2025');
                    
                CREATE TABLE adbms_demo_partitionedenrollment_spring2026 
                    PARTITION OF adbms_demo_partitionedenrollment 
                    FOR VALUES IN ('Spring 2026');
            """,
            reverse_sql="""
                DROP TABLE IF EXISTS adbms_demo_partitionedenrollment CASCADE;
            """
        ),
    ]
