# Generated by Django 5.2.8 on 2025-11-23 16:22
# Modified to add PL/pgSQL trigger functions for audit logging

from django.db import migrations, models


def create_audit_triggers(apps, schema_editor):
    """
    Create PL/pgSQL trigger functions and attach them to 4 tables:
    - enrollment_enrollment
    - courses_course
    - courses_section
    - enrollment_waitlist
    """
    
    # SQL to create trigger function for Enrollment table
    enrollment_trigger_sql = """
    CREATE OR REPLACE FUNCTION audit_enrollment_changes()
    RETURNS TRIGGER AS $$
    DECLARE
        change_summary_text TEXT;
        old_json JSONB;
        new_json JSONB;
    BEGIN
        -- Build JSON representations
        IF TG_OP = 'DELETE' THEN
            old_json = to_jsonb(OLD);
            new_json = NULL;
            change_summary_text = 'Enrollment deleted: Student ID ' || OLD.student_id || 
                                 ' dropped from Section ID ' || OLD.section_id;
        ELSIF TG_OP = 'INSERT' THEN
            old_json = NULL;
            new_json = to_jsonb(NEW);
            change_summary_text = 'New enrollment: Student ID ' || NEW.student_id || 
                                 ' enrolled in Section ID ' || NEW.section_id;
        ELSE  -- UPDATE
            old_json = to_jsonb(OLD);
            new_json = to_jsonb(NEW);
            
            -- Detect what changed
            IF OLD.grade IS DISTINCT FROM NEW.grade THEN
                change_summary_text = 'Grade changed from ' || 
                                     COALESCE(OLD.grade, 'NULL') || ' to ' || 
                                     COALESCE(NEW.grade, 'NULL') || 
                                     ' for Student ID ' || NEW.student_id;
            ELSE
                change_summary_text = 'Enrollment updated for Student ID ' || NEW.student_id;
            END IF;
        END IF;
        
        -- Insert audit record
        INSERT INTO adbms_demo_auditlog (
            table_name, operation, record_id, old_data, new_data, 
            changed_at, change_summary, changed_by
        ) VALUES (
            'enrollment_enrollment',
            TG_OP,
            COALESCE(NEW.id, OLD.id),
            old_json,
            new_json,
            NOW(),
            change_summary_text,
            current_user
        );
        
        -- Return appropriate value
        IF TG_OP = 'DELETE' THEN
            RETURN OLD;
        ELSE
            RETURN NEW;
        END IF;
    END;
    $$ LANGUAGE plpgsql;
    
    -- Create triggers for Enrollment
    DROP TRIGGER IF EXISTS enrollment_audit_insert ON enrollment_enrollment;
    CREATE TRIGGER enrollment_audit_insert
        AFTER INSERT ON enrollment_enrollment
        FOR EACH ROW EXECUTE FUNCTION audit_enrollment_changes();
    
    DROP TRIGGER IF EXISTS enrollment_audit_update ON enrollment_enrollment;
    CREATE TRIGGER enrollment_audit_update
        AFTER UPDATE ON enrollment_enrollment
        FOR EACH ROW EXECUTE FUNCTION audit_enrollment_changes();
    
    DROP TRIGGER IF EXISTS enrollment_audit_delete ON enrollment_enrollment;
    CREATE TRIGGER enrollment_audit_delete
        AFTER DELETE ON enrollment_enrollment
        FOR EACH ROW EXECUTE FUNCTION audit_enrollment_changes();
    """
    
    # SQL to create trigger function for Course table
    course_trigger_sql = """
    CREATE OR REPLACE FUNCTION audit_course_changes()
    RETURNS TRIGGER AS $$
    DECLARE
        change_summary_text TEXT;
        old_json JSONB;
        new_json JSONB;
    BEGIN
        IF TG_OP = 'DELETE' THEN
            old_json = to_jsonb(OLD);
            new_json = NULL;
            change_summary_text = 'Course deleted: ' || OLD.code || ' - ' || OLD.title;
        ELSIF TG_OP = 'INSERT' THEN
            old_json = NULL;
            new_json = to_jsonb(NEW);
            change_summary_text = 'New course created: ' || NEW.code || ' - ' || NEW.title || 
                                 ' (' || NEW.credits || ' credits)';
        ELSE  -- UPDATE
            old_json = to_jsonb(OLD);
            new_json = to_jsonb(NEW);
            
            -- Detect what changed
            IF OLD.title != NEW.title THEN
                change_summary_text = 'Course title changed from "' || OLD.title || 
                                     '" to "' || NEW.title || '"';
            ELSIF OLD.credits != NEW.credits THEN
                change_summary_text = 'Credits changed from ' || OLD.credits || 
                                     ' to ' || NEW.credits || ' for ' || NEW.code;
            ELSIF OLD.description != NEW.description THEN
                change_summary_text = 'Description updated for ' || NEW.code;
            ELSE
                change_summary_text = 'Course updated: ' || NEW.code;
            END IF;
        END IF;
        
        INSERT INTO adbms_demo_auditlog (
            table_name, operation, record_id, old_data, new_data, 
            changed_at, change_summary, changed_by
        ) VALUES (
            'courses_course',
            TG_OP,
            COALESCE(NEW.id, OLD.id),
            old_json,
            new_json,
            NOW(),
            change_summary_text,
            current_user
        );
        
        IF TG_OP = 'DELETE' THEN
            RETURN OLD;
        ELSE
            RETURN NEW;
        END IF;
    END;
    $$ LANGUAGE plpgsql;
    
    -- Create triggers for Course
    DROP TRIGGER IF EXISTS course_audit_insert ON courses_course;
    CREATE TRIGGER course_audit_insert
        AFTER INSERT ON courses_course
        FOR EACH ROW EXECUTE FUNCTION audit_course_changes();
    
    DROP TRIGGER IF EXISTS course_audit_update ON courses_course;
    CREATE TRIGGER course_audit_update
        AFTER UPDATE ON courses_course
        FOR EACH ROW EXECUTE FUNCTION audit_course_changes();
    
    DROP TRIGGER IF EXISTS course_audit_delete ON courses_course;
    CREATE TRIGGER course_audit_delete
        AFTER DELETE ON courses_course
        FOR EACH ROW EXECUTE FUNCTION audit_course_changes();
    """
    
    # SQL to create trigger function for Section table
    section_trigger_sql = """
    CREATE OR REPLACE FUNCTION audit_section_changes()
    RETURNS TRIGGER AS $$
    DECLARE
        change_summary_text TEXT;
        old_json JSONB;
        new_json JSONB;
    BEGIN
        IF TG_OP = 'DELETE' THEN
            old_json = to_jsonb(OLD);
            new_json = NULL;
            change_summary_text = 'Section deleted: ID ' || OLD.id || 
                                 ' (Course ID ' || OLD.course_id || ', ' || OLD.semester || ')';
        ELSIF TG_OP = 'INSERT' THEN
            old_json = NULL;
            new_json = to_jsonb(NEW);
            change_summary_text = 'New section created: ID ' || NEW.id || 
                                 ' for Course ID ' || NEW.course_id || 
                                 ' (' || NEW.semester || ', Capacity: ' || NEW.capacity || ')';
        ELSE  -- UPDATE
            old_json = to_jsonb(OLD);
            new_json = to_jsonb(NEW);
            
            -- Detect what changed
            IF OLD.capacity != NEW.capacity THEN
                change_summary_text = 'Capacity changed from ' || OLD.capacity || 
                                     ' to ' || NEW.capacity || ' for Section ID ' || NEW.id;
            ELSIF OLD.schedule != NEW.schedule THEN
                change_summary_text = 'Schedule changed from "' || OLD.schedule || 
                                     '" to "' || NEW.schedule || '" for Section ID ' || NEW.id;
            ELSIF OLD.room_number != NEW.room_number THEN
                change_summary_text = 'Room changed from ' || OLD.room_number || 
                                     ' to ' || NEW.room_number || ' for Section ID ' || NEW.id;
            ELSIF OLD.instructor_id IS DISTINCT FROM NEW.instructor_id THEN
                change_summary_text = 'Instructor changed for Section ID ' || NEW.id;
            ELSE
                change_summary_text = 'Section updated: ID ' || NEW.id;
            END IF;
        END IF;
        
        INSERT INTO adbms_demo_auditlog (
            table_name, operation, record_id, old_data, new_data, 
            changed_at, change_summary, changed_by
        ) VALUES (
            'courses_section',
            TG_OP,
            COALESCE(NEW.id, OLD.id),
            old_json,
            new_json,
            NOW(),
            change_summary_text,
            current_user
        );
        
        IF TG_OP = 'DELETE' THEN
            RETURN OLD;
        ELSE
            RETURN NEW;
        END IF;
    END;
    $$ LANGUAGE plpgsql;
    
    -- Create triggers for Section
    DROP TRIGGER IF EXISTS section_audit_insert ON courses_section;
    CREATE TRIGGER section_audit_insert
        AFTER INSERT ON courses_section
        FOR EACH ROW EXECUTE FUNCTION audit_section_changes();
    
    DROP TRIGGER IF EXISTS section_audit_update ON courses_section;
    CREATE TRIGGER section_audit_update
        AFTER UPDATE ON courses_section
        FOR EACH ROW EXECUTE FUNCTION audit_section_changes();
    
    DROP TRIGGER IF EXISTS section_audit_delete ON courses_section;
    CREATE TRIGGER section_audit_delete
        AFTER DELETE ON courses_section
        FOR EACH ROW EXECUTE FUNCTION audit_section_changes();
    """
    
    # SQL to create trigger function for Waitlist table
    waitlist_trigger_sql = """
    CREATE OR REPLACE FUNCTION audit_waitlist_changes()
    RETURNS TRIGGER AS $$
    DECLARE
        change_summary_text TEXT;
        old_json JSONB;
        new_json JSONB;
    BEGIN
        IF TG_OP = 'DELETE' THEN
            old_json = to_jsonb(OLD);
            new_json = NULL;
            change_summary_text = 'Waitlist entry removed: Student ID ' || OLD.student_id || 
                                 ' for Section ID ' || OLD.section_id;
        ELSIF TG_OP = 'INSERT' THEN
            old_json = NULL;
            new_json = to_jsonb(NEW);
            change_summary_text = 'Student ID ' || NEW.student_id || 
                                 ' added to waitlist for Section ID ' || NEW.section_id;
        ELSE  -- UPDATE
            old_json = to_jsonb(OLD);
            new_json = to_jsonb(NEW);
            
            -- Detect what changed
            IF OLD.notified != NEW.notified THEN
                IF NEW.notified THEN
                    change_summary_text = 'Student ID ' || NEW.student_id || 
                                         ' notified for Section ID ' || NEW.section_id;
                ELSE
                    change_summary_text = 'Notification status reset for Student ID ' || NEW.student_id;
                END IF;
            ELSE
                change_summary_text = 'Waitlist entry updated for Student ID ' || NEW.student_id;
            END IF;
        END IF;
        
        INSERT INTO adbms_demo_auditlog (
            table_name, operation, record_id, old_data, new_data, 
            changed_at, change_summary, changed_by
        ) VALUES (
            'enrollment_waitlist',
            TG_OP,
            COALESCE(NEW.id, OLD.id),
            old_json,
            new_json,
            NOW(),
            change_summary_text,
            current_user
        );
        
        IF TG_OP = 'DELETE' THEN
            RETURN OLD;
        ELSE
            RETURN NEW;
        END IF;
    END;
    $$ LANGUAGE plpgsql;
    
    -- Create triggers for Waitlist
    DROP TRIGGER IF EXISTS waitlist_audit_insert ON enrollment_waitlist;
    CREATE TRIGGER waitlist_audit_insert
        AFTER INSERT ON enrollment_waitlist
        FOR EACH ROW EXECUTE FUNCTION audit_waitlist_changes();
    
    DROP TRIGGER IF EXISTS waitlist_audit_update ON enrollment_waitlist;
    CREATE TRIGGER waitlist_audit_update
        AFTER UPDATE ON enrollment_waitlist
        FOR EACH ROW EXECUTE FUNCTION audit_waitlist_changes();
    
    DROP TRIGGER IF EXISTS waitlist_audit_delete ON enrollment_waitlist;
    CREATE TRIGGER waitlist_audit_delete
        AFTER DELETE ON enrollment_waitlist
        FOR EACH ROW EXECUTE FUNCTION audit_waitlist_changes();
    """
    
    # Execute all SQL
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(enrollment_trigger_sql)
        cursor.execute(course_trigger_sql)
        cursor.execute(section_trigger_sql)
        cursor.execute(waitlist_trigger_sql)


def drop_audit_triggers(apps, schema_editor):
    """
    Remove all audit triggers and functions.
    """
    drop_sql = """
    -- Drop Enrollment triggers and function
    DROP TRIGGER IF EXISTS enrollment_audit_insert ON enrollment_enrollment;
    DROP TRIGGER IF EXISTS enrollment_audit_update ON enrollment_enrollment;
    DROP TRIGGER IF EXISTS enrollment_audit_delete ON enrollment_enrollment;
    DROP FUNCTION IF EXISTS audit_enrollment_changes();
    
    -- Drop Course triggers and function
    DROP TRIGGER IF EXISTS course_audit_insert ON courses_course;
    DROP TRIGGER IF EXISTS course_audit_update ON courses_course;
    DROP TRIGGER IF EXISTS course_audit_delete ON courses_course;
    DROP FUNCTION IF EXISTS audit_course_changes();
    
    -- Drop Section triggers and function
    DROP TRIGGER IF EXISTS section_audit_insert ON courses_section;
    DROP TRIGGER IF EXISTS section_audit_update ON courses_section;
    DROP TRIGGER IF EXISTS section_audit_delete ON courses_section;
    DROP FUNCTION IF EXISTS audit_section_changes();
    
    -- Drop Waitlist triggers and function
    DROP TRIGGER IF EXISTS waitlist_audit_insert ON enrollment_waitlist;
    DROP TRIGGER IF EXISTS waitlist_audit_update ON enrollment_waitlist;
    DROP TRIGGER IF EXISTS waitlist_audit_delete ON enrollment_waitlist;
    DROP FUNCTION IF EXISTS audit_waitlist_changes();
    """
    
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(drop_sql)


class Migration(migrations.Migration):

    dependencies = [
        ('adbms_demo', '0001_initial'),
        ('courses', '0002_initial'),
        ('enrollment', '0003_waitlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(help_text="Name of the audited table (e.g., 'enrollment_enrollment')", max_length=100)),
                ('operation', models.CharField(choices=[('INSERT', 'Insert'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], help_text='Type of operation performed', max_length=10)),
                ('record_id', models.IntegerField(help_text='ID of the affected record')),
                ('old_data', models.JSONField(blank=True, help_text='Previous state of the record (for UPDATE/DELETE)', null=True)),
                ('new_data', models.JSONField(blank=True, help_text='New state of the record (for INSERT/UPDATE)', null=True)),
                ('changed_by', models.CharField(blank=True, help_text='Username or session info if available', max_length=255, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the change occurred')),
                ('change_summary', models.TextField(blank=True, help_text='Human-readable description of the change')),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['table_name', '-changed_at'], name='adbms_demo__table_n_b87f0d_idx'), models.Index(fields=['operation', '-changed_at'], name='adbms_demo__operati_2c4ec7_idx'), models.Index(fields=['record_id', 'table_name'], name='adbms_demo__record__ce4c3f_idx')],
            },
        ),
        # Add custom SQL to create trigger functions
        migrations.RunPython(create_audit_triggers, reverse_code=drop_audit_triggers),
    ]
