# Generated by Django 5.2.8 on 2025-11-23 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adbms_demo', '0002_auditlog'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE MATERIALIZED VIEW adbms_demo_materialized_enrollment AS
            SELECT
                row_number() OVER () AS id,
                u.username as student_name,
                c.code as course_code,
                c.title as course_title,
                s.semester as semester,
                e.grade as grade,
                c.credits as credits
            FROM
                enrollment_enrollment e
            JOIN
                users_user u ON e.student_id = u.id
            JOIN
                courses_section s ON e.section_id = s.id
            JOIN
                courses_course c ON s.course_id = c.id;
            """,
            reverse_sql="DROP MATERIALIZED VIEW IF EXISTS adbms_demo_materialized_enrollment;"
        )
    ]
