# Generated by Django 5.2.9 on 2025-12-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adbms_demo', '0004_enable_pg_stat_statements'),
    ]

    operations = [
        migrations.CreateModel(
            name='DenormalizedEnrollment',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=150)),
                ('course_code', models.CharField(max_length=20)),
                ('course_title', models.CharField(max_length=200)),
                ('semester', models.CharField(max_length=20)),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('credits', models.IntegerField()),
            ],
            options={
                'db_table': 'adbms_demo_materialized_enrollment',
                'managed': False,
            },
        ),
    ]
