# Generated by Django 5.2.9 on 2025-12-25 10:58

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('title', 'description', config='english'), name='course_search_vector_idx'),
        ),
    ]
