# Generated by Django 5.2.8 on 2025-11-23 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('enrollment', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False, help_text='Whether the student has been notified of enrollment')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlists', to='courses.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
                'indexes': [models.Index(fields=['section', 'joined_at'], name='enrollment__section_bcccf3_idx'), models.Index(fields=['student'], name='enrollment__student_6b1b66_idx')],
                'unique_together': {('student', 'section')},
            },
        ),
    ]
